添加update请求

diff --git a/tools/lminstall/lminstall b/tools/lminstall/lminstall
--- a/tools/lminstall/lminstall
+++ b/tools/lminstall/lminstall
@@ -12,38 +12,12 @@ case $(arch) in
 	;;
 esac
 
-echo "Spark Store Install script. 星火商店审核脚本"
+echo "LingmoOS Install script. LingmoOS安装脚本"
 
 function pkexec_as_current_user() {
     local user=$(who | awk '{print $1}' | head -n 1)
     local uid=$(id -u "$user")
     sudo -u "$user" DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/"$uid"/bus pkexec "$@"
-}
-function create_desktop_file() {
-	local user=$(who | awk '{print $1}' | head -n 1)
-	if [ -e $(sudo -u "$user" xdg-user-dir)/.config/spark-union/spark-store/ssshell-config-do-not-create-desktop ];then
-	echo "It is configured that do not create desktop file. Give up"
-	else
-	exec_create_desktop_file
-	fi
-}
-function exec_create_desktop_file() {
-    local user=$(who | awk '{print $1}' | head -n 1)
-    for desktop_file_path in $(dpkg -L "$package_name" |grep /usr/share/applications/ | awk '/\.desktop$/ {print}'); do
-	if [ "$(cat $desktop_file_path | grep NoDisplay=true)" = "" ];then
-	echo $desktop_file_path is checked and will be installed to desktop
-        sudo -u "$user" cp "$desktop_file_path" "$(sudo -u "$user" xdg-user-dir DESKTOP)/"
-	fi
-    done
-	for desktop_file_path in $(dpkg -L "$package_name" |grep /opt/apps/$package_name/entries/applications | awk '/\.desktop$/ {print}'); do
-	if [ "$(cat $desktop_file_path | grep NoDisplay=true)" = "" ];then
-	echo $desktop_file_path is checked and will be installed to desktop
-        chmod +x $desktop_file_path
-        sudo -u "$user" cp "$desktop_file_path" "$(sudo -u "$user" xdg-user-dir DESKTOP)/"
-	fi
-    done
-
-
 }
 
 function zenity() {
@@ -53,19 +27,19 @@ function zenity() {
 }
 
 function hash_check() {
-    if [ ! -e "/var/lib/aptss/lists/cdn.d.store.deepinos.org.cn_${STORE_URL}_Packages" ] && \
+    if [ ! -e "/var/lib/aptss/lists/d.spark-app.store_${STORE_URL}_Packages" ] && \
        [ ! -e "/var/lib/aptss/lists/d.store.deepinos.org.cn_${STORE_URL}_Packages" ] && \
        [ ! -e "/var/lib/aptss/lists/mirrors.sdu.edu.cn_spark-store-repository_${STORE_URL}_Packages" ]; then
         echo "接收星火仓库软件信息中..."
-        aptss ssupdate
+        bash /usr/share/lingmo-settings/tools/aptlm/aptlm ssupdate
     fi
 
-    if [ -e "/var/lib/aptss/lists/cdn.d.store.deepinos.org.cn_${STORE_URL}_Packages" ]; then
-        PACKAGES_DATA_PATH="/var/lib/aptss/lists/cdn.d.store.deepinos.org.cn_${STORE_URL}_Packages"
-        echo "星火仓库的Packages位置为 $PACKAGES_DATA_PATH，是星火域名单目录仓库配置"
+    if [ -e "/var/lib/aptss/lists/d.spark-app.store_${STORE_URL}_Packages" ]; then
+        PACKAGES_DATA_PATH="/var/lib/aptss/lists/d.spark-app.store_${STORE_URL}_Packages"
+        echo "星火仓库的Packages位置为 $PACKAGES_DATA_PATH，是星火域名仓库配置"
     elif [ -e "/var/lib/aptss/lists/d.store.deepinos.org.cn_${STORE_URL}_Packages" ]; then
         PACKAGES_DATA_PATH="/var/lib/aptss/lists/d.store.deepinos.org.cn_${STORE_URL}_Packages"
-        echo "星火仓库的Packages位置为 $PACKAGES_DATA_PATH，是星火域名单目录仓库配置"
+        echo "星火仓库的Packages位置为 $PACKAGES_DATA_PATH，是d域名单目录仓库配置"
     else
         PACKAGES_DATA_PATH="/var/lib/aptss/lists/mirrors.sdu.edu.cn_spark-store-repository_${STORE_URL}_Packages"
         echo "星火仓库的Packages位置为 $PACKAGES_DATA_PATH，是SDU镜像仓库配置"
@@ -103,20 +77,35 @@ fi
 
 DEBPATH=$(realpath "$1")
 
+hash_check "$DEBPATH"
 
+if [ -z "$IS_SHA512SUM_CHECKED" ]; then
+    echo "尝试更新仓库信息重新校验"
+    aptss ssupdate
+    hash_check "$DEBPATH"
+	if [ -z "$IS_SHA512SUM_CHECKED" ]; then
+	echo -e "$TRANSHELL_CONTENT_HASH_CHECK_FAILED"
+	zenity --info --icon-name=spark-store --height 270 --width 500 --text "$TRANSHELL_CONTENT_HASH_CHECK_FAILED"
+	echo  "OMG-IT-GOES-WRONG"
+	exit 1
+	fi
+fi
 
+if [ ! -z "$IS_SHA512SUM_CHECKED" ]; then
+    echo "校验成功，开始安装"
+    echo "----------------------------------------------------------------------------------"
     package_name=$(dpkg-deb -f "$DEBPATH" Package)
     echo "Package name is $package_name"
-    
     try_run_output=$(/opt/durapps/spark-store/bin/update-upgrade/ss-do-upgrade-worker.sh test-install-app "$DEBPATH")
     try_run_ret="$?"
+
     if [ "$try_run_ret" -ne 0 ]; then
     aptss update
     try_run_output=$(/opt/durapps/spark-store/bin/update-upgrade/ss-do-upgrade-worker.sh test-install-app "$DEBPATH")
     try_run_ret="$?"
     fi
-
-    if [ "$try_run_ret" -ne 0 ]; then
+    
+     if [ "$try_run_ret" -ne 0 ]; then
         echo "OMG-IT-GOES-WRONG"
         echo -e "${try_run_output}"
         exit "$try_run_ret"
@@ -146,3 +135,5 @@ DEBPATH=$(realpath "$1")
             echo "OMG-IT-GOES-WRONG"
         fi
     fi
+fi
+
